Repository team-animal-farm/animal-logistics, pull requests merged in 2024-09, with the labels that each got.

#1 fix: 루트 패키지에서 하위 패키지로 이동
  common/common/src/main/java/response/CommonResponse.java
  common/common/src/main/java/response/ErrorCase.java
  component/component-exception/src/main/java/exception/GlobalException.java
  component/component-exception/src/main/java/exception/GlobalExceptionHandler.java
  component/component-exception/src/main/java/exception/InvalidInputMapper.java
  component/component-exception/src/main/java/exception/InvalidInputRes.java
  component/component-jpa/src/main/java/jpa/BaseEntity.java
  component/component-jpa/src/main/java/jpa/JpaAuditingConfig.java
Labels: bug

#2 feat: 프로젝트 설정 추가
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/버그-수정.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  application/auth/Dockerfile
  application/auth/build.gradle
  application/auth/docker-compose.yml
  application/auth/src/main/resources/application-dev.yml
  application/auth/src/main/resources/application.yml
  application/company/Dockerfile
  application/company/build.gradle
  application/company/docker-compose.yml
  application/company/src/main/resources/application-dev.yml
  application/company/src/main/resources/application.yml
  application/hub/Dockerfile
  application/hub/build.gradle
  application/hub/docker-compose.yml
  application/hub/src/main/java/ex/HubApplication.java
  application/hub/src/main/resources/application-dev.yml
  application/hub/src/main/resources/application.yml
  application/hub/src/test/java/ex/hub/HubApplicationTests.java
  application/notification/Dockerfile
  application/notification/build.gradle
  application/notification/docker-compose.yml
  application/notification/src/main/resources/application-dev.yml
  application/notification/src/main/resources/application.yml
  application/order/Dockerfile
  application/order/build.gradle
  application/order/docker-compose.yml
  application/order/src/main/resources/application-dev.yml
  application/order/src/main/resources/application.yml
  conventions/README.md
  conventions/directory/README.md
  conventions/exception/README.md
  conventions/git-branch/README.md
  conventions/response/README.md
  conventions/style/README.md
  conventions/style/intellij-java-google-style.xml
  docs/images/animal-farm-v1.png
  docs/images/github-flow.png
  docs/images/sample-squirrel.jpg
  docs/images/step01.png
  docs/images/step02.png
  docs/images/step03.png
Labels: enhancement

#9 feat: company 기능 추가, BaseEntity 설정
  application/auth/src/main/java/animal/domain/User.java
  application/auth/src/main/resources/application.yml
  application/company/build.gradle
  application/company/http/company-api.http
  application/company/http/http-client.env.json
  application/company/src/main/java/animal/application/CompanyService.java
  application/company/src/main/java/animal/config/ComponentConfig.java
  application/company/src/main/java/animal/domain/Company.java
  application/company/src/main/java/animal/domain/CompanyId.java
  application/company/src/main/java/animal/domain/Product.java
  application/company/src/main/java/animal/dto/CompanyRequest.java
  application/company/src/main/java/animal/dto/CompanyResponse.java
  application/company/src/main/java/animal/infrastructure/CompanyRepository.java
  application/company/src/main/java/animal/mapper/CompanyMapper.java
  application/company/src/main/java/animal/presentation/CompanyController.java
  application/company/src/main/resources/application-dev.yml
  application/company/src/main/resources/application.yml
  application/hub/src/main/java/animal/domain/Hub.java
  application/hub/src/main/resources/application.yml
  common/common/src/main/java/response/CompanyStatus.java
  common/common/src/main/java/response/CompanyType.java
  common/common/src/main/java/response/ErrorCase.java
  component/component-jpa/src/main/java/animal/jpa/AuditorAwareImpl.java
  component/component-jpa/src/main/java/animal/jpa/BaseEntity.java
  component/component-jpa/src/main/java/animal/jpa/JpaAuditingConfig.java
  component/component-jpa/src/main/java/jpa/BaseEntity.java
Labels: enhancement

#10 feat: 재고 도메인 API 추가
  application/hub/http/http-client.env.json
  application/hub/http/hub-api.http
  application/hub/src/main/java/animal/application/InventoryService.java
  application/hub/src/main/java/animal/domain/Hub.java
  application/hub/src/main/java/animal/domain/Inventory.java
  application/hub/src/main/java/animal/domain/InventoryId.java
  application/hub/src/main/java/animal/domain/Money.java
  application/hub/src/main/java/animal/domain/Quantity.java
  application/hub/src/main/java/animal/dto/InventoryRequest.java
  application/hub/src/main/java/animal/dto/InventoryResponse.java
  application/hub/src/main/java/animal/mapper/InventoryMapper.java
  application/hub/src/main/java/animal/presentation/InventoryController.java
  application/hub/src/main/resources/application-dev.yml
Labels: enhancement

#12 feat(company): 업체 검색 초기 구현 (차후 querydsl로 리팩토링 예정)
  application/company/http/company-api.http
  application/company/http/http-client.env.json
  application/company/src/main/java/animal/application/CompanyService.java
  application/company/src/main/java/animal/dto/CompanyResponse.java
  application/company/src/main/java/animal/infrastructure/CompanyRepository.java
  application/company/src/main/java/animal/presentation/CompanyController.java
Labels: enhancement

#14 feat: 매니저 조회 및 추가 API 구현
  application/hub/http/hub-api.http
  application/hub/src/main/java/animal/application/HubService.java
  application/hub/src/main/java/animal/application/InventoryService.java
  application/hub/src/main/java/animal/application/ManagerService.java
  application/hub/src/main/java/animal/domain/Hub.java
  application/hub/src/main/java/animal/domain/Inventory.java
  application/hub/src/main/java/animal/domain/manager/CompanyDeliveryManager.java
  application/hub/src/main/java/animal/domain/manager/HubDeliveryManager.java
  application/hub/src/main/java/animal/domain/manager/HubManager.java
  application/hub/src/main/java/animal/domain/manager/ProviderCompanyManager.java
  application/hub/src/main/java/animal/domain/manager/SlackId.java
  application/hub/src/main/java/animal/domain/manager/Username.java
  application/hub/src/main/java/animal/dto/HubResponse.java
  application/hub/src/main/java/animal/dto/ManagerRequest.java
  application/hub/src/main/java/animal/dto/ManagerResponse.java
  application/hub/src/main/java/animal/mapper/HubMapper.java
  application/hub/src/main/java/animal/presentation/ManagerController.java
  common/common/src/main/java/response/ErrorCase.java
Labels: enhancement

#16 feat(product) : Product 관련 API 개발
  application/company/http/company-api.http
  application/company/http/http-client.env.json
  application/company/src/main/java/animal/application/CompanyService.java
  application/company/src/main/java/animal/application/ProductService.java
  application/company/src/main/java/animal/domain/Company.java
  application/company/src/main/java/animal/domain/Product.java
  application/company/src/main/java/animal/domain/ProductId.java
  application/company/src/main/java/animal/dto/CompanyRequest.java
  application/company/src/main/java/animal/dto/ProductRequest.java
  application/company/src/main/java/animal/dto/ProductResponse.java
  application/company/src/main/java/animal/infrastructure/ProductRepository.java
  application/company/src/main/java/animal/mapper/ProductMapper.java
  application/company/src/main/java/animal/presentation/ProductController.java
  common/common/src/main/java/response/ErrorCase.java
Labels: enhancement

#18 feat: 스프링 배치 추가
  application/order/build.gradle
  application/order/src/main/java/animal/application/order/OrderApplication.java
  application/order/src/main/java/animal/application/order/application/HubDeliveryService.java
  application/order/src/main/java/animal/application/order/config/BatchConfig.java
  application/order/src/main/resources/batch-schema.sql
Labels: enhancement

#17 feat: 허브 도메인 보강
  application/hub/build.gradle
  application/hub/http/hub-api.http
  application/hub/src/main/java/animal/application/InventoryService.java
  application/hub/src/main/java/animal/config/PropertyConfig.java
  application/hub/src/main/java/animal/config/SwaggerConfig.java
  application/hub/src/main/java/animal/domain/Address.java
  application/hub/src/main/java/animal/domain/Coordinate.java
  application/hub/src/main/java/animal/domain/Hub.java
  application/hub/src/main/java/animal/dto/InventoryRequest.java
  application/hub/src/main/java/animal/presentation/InventoryController.java
  application/hub/src/main/java/animal/property/HubProperty.java
  application/hub/src/main/java/animal/property/HubPropertyList.java
  application/hub/src/main/java/animal/property/PropertyInitializer.java
  application/hub/src/main/resources/application-dev.yml
  application/hub/src/main/resources/application.yml
Labels: enhancement

#21 feat: 배송 도메인 추가
  application/order/src/main/java/animal/application/order/domain/delivery/Address.java
  application/order/src/main/java/animal/application/order/domain/delivery/Delivery.java
  application/order/src/main/java/animal/application/order/domain/delivery/DeliveryPath.java
  application/order/src/main/java/animal/application/order/domain/delivery/DeliveryStatus.java
  application/order/src/main/java/animal/application/order/domain/delivery/HubPath.java
  application/order/src/main/java/animal/application/order/infrastructure/DeliveryRepository.java
  application/order/src/main/resources/application-dev.yml
Labels: enhancement

#20 Feat/user add circuitBreaker
  application/auth/build.gradle
  application/auth/src/main/java/animal/auth/application/HubClient.java
  application/auth/src/main/java/animal/auth/application/HubFallbackFactory.java
  application/auth/src/main/java/animal/auth/application/UserService.java
  application/auth/src/main/java/animal/auth/config/HubFeignClientConfig.java
  application/auth/src/main/java/animal/auth/config/Resilience4jConfig.java
  application/auth/src/main/java/animal/auth/domain/CompanyUser.java
  application/auth/src/main/java/animal/auth/domain/DeliveryUser.java
  application/auth/src/main/java/animal/auth/dto/UserRequest.java
  application/auth/src/main/java/animal/auth/dto/UserResponse.java
  application/auth/src/main/java/animal/auth/infrastructure/UserRepository.java
  application/auth/src/main/java/animal/auth/mapper/UserMapper.java
  application/auth/src/main/java/animal/auth/presentation/UserController.java
  application/auth/src/test/http/UserHttp.http
  application/auth/src/test/java/animal/auth/application/FeignClientTest.java
  application/auth/src/test/java/animal/auth/presentation/UserControllerTest.java
  common/common/src/main/java/response/ErrorCase.java
  component/component-security/src/main/java/security/UserRole.java
Labels: enhancement

#22 feat: 알림 도메인 추가
  application/notification/src/main/java/animal/application/notification/NotificationApplication.java
  application/notification/src/main/java/animal/application/notification/application/NotificationSendService.java
  application/notification/src/main/java/animal/application/notification/config/PropertyConfig.java
  application/notification/src/main/java/animal/application/notification/config/RestTemplateConfig.java
  application/notification/src/main/java/animal/application/notification/domain/Notification.java
  application/notification/src/main/java/animal/application/notification/domain/Platform.java
  application/notification/src/main/java/animal/application/notification/domain/Prompt.java
  application/notification/src/main/java/animal/application/notification/implementation/NotificationSaver.java
  application/notification/src/main/java/animal/application/notification/implementation/NotificationSender.java
  application/notification/src/main/java/animal/application/notification/implementation/PromptCreator.java
  application/notification/src/main/java/animal/application/notification/implementation/PromptSender.java
  application/notification/src/main/java/animal/application/notification/infrastructure/NotificationRepository.java
  application/notification/src/main/java/animal/application/notification/property/AiProperty.java
  application/notification/src/main/resources/application-dev.yml
Labels: enhancement

#29 feat: 허브 배송 담당자 로직 보강
  application/hub/build.gradle
  application/order/src/main/java/animal/application/order/application/DeliveryReader.java
  application/order/src/main/java/animal/application/order/application/DeliveryService.java
  application/order/src/main/java/animal/application/order/application/HubDeliveryAssigner.java
  application/order/src/main/java/animal/application/order/infrastructure/order/DeliveryRepository.java
Labels: enhancement

#30 업체배송 API 수정
  application/auth/src/main/java/animal/auth/AuthApplication.java
  application/auth/src/main/java/animal/auth/application/UserService.java
  application/auth/src/main/java/animal/auth/dto/UserResponse.java
  application/auth/src/main/java/animal/auth/infrastructure/UserRepository.java
  application/auth/src/main/java/animal/auth/mapper/UserMapper.java
  application/auth/src/main/java/animal/auth/presentation/UserController.java
  application/company/src/main/java/animal/application/CompanyService.java
  application/company/src/main/java/animal/dto/CompanyResponse.java
  application/company/src/main/java/animal/presentation/CompanyController.java
  application/hub/build.gradle
  application/order/src/main/java/animal/application/order/application/CompanyDeliveryService.java
  application/order/src/main/java/animal/application/order/application/DeliveryService.java
  application/order/src/main/java/animal/application/order/application/SlackService.java
  application/order/src/main/java/animal/application/order/application/order/CompanyClient.java
  application/order/src/main/java/animal/application/order/application/order/HubClient.java
  application/order/src/main/java/animal/application/order/application/order/OrderService.java
  application/order/src/main/java/animal/application/order/client/CompanyClient.java
  application/order/src/main/java/animal/application/order/client/HubClient.java
  application/order/src/main/java/animal/application/order/domain/delivery/Delivery.java
  application/order/src/main/java/animal/application/order/dto/OrderResponse.java
  application/order/src/main/java/animal/application/order/dto/hub/HubResponse.java
  application/order/src/main/java/animal/application/order/dto/slack/SlackIncomingHookDto.java
  application/order/src/main/java/animal/application/order/dto/user/UserResponse.java
  application/order/src/main/java/animal/application/order/infrastructure/hub/HubClient.java
  application/order/src/main/java/animal/application/order/infrastructure/hub/HubFallbackFactory.java
  application/order/src/main/java/animal/application/order/infrastructure/user/UserClient.java
  application/order/src/main/resources/application-dev.yml
  component/component-security/src/main/java/security/JwtUtil.java
Labels: enhancement

#31 docs: README 보강
  README.md
  application/auth/build.gradle
  application/auth/src/main/java/animal/auth/config/SwaggerConfig.java
  application/company/build.gradle
  application/company/src/main/java/animal/config/SwaggerConfig.java
  application/gateway/build.gradle
  application/notification/build.gradle
  application/notification/src/main/java/animal/application/notification/config/SwaggerConfig.java
  application/order/build.gradle
  application/order/src/main/java/animal/application/order/config/SwaggerConfig.java
  docs/images/animal-farm-ddd.png
  docs/images/animal-farm-event-storming.png
  docs/images/animal-farm-infra-v1.png
  docs/images/animal-farm-v2.png
Labels: documentation

#33 feat: 허브에 캐싱 추가
  application/hub/build.gradle
  application/hub/docker-compose.yml
  application/hub/src/main/java/animal/application/HubService.java
  application/hub/src/main/java/animal/config/RedisConfig.java
  application/hub/src/main/resources/application-dev.yml
Labels: enhancement

#35 feat: 업체 담당자 더미 데이터 추가
  application/hub/src/main/java/animal/application/ManagerService.java
  application/hub/src/main/java/animal/dto/ManagerRequest.java
  application/hub/src/main/java/animal/property/PropertyInitializer.java
Labels: enhancement

#37 feat: 리드미 수정
  README.md
  docs/images/animal-farm-infra-v2.png
Labels: documentation
